# Generated by Django 3.1.1 on 2022-04-21 13:54

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decor', '0001_initial'),
        ('postbacks', '0001_initial'),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('color', models.CharField(blank=True, choices=[('blue-band.png', 'Blue'), ('darkblue-band.png', 'DarkBlue'), ('red-band.png', 'Red'), ('green-band.png', 'Green'), ('yellow-band.png', 'Yellow'), ('violet-band.png', 'Violet'), ('purple-band.png', 'Purple'), ('orange-band.png', 'Orange')], max_length=50, null=True, verbose_name='Color')),
                ('text', models.CharField(blank=True, max_length=10, null=True, verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
            },
        ),
        migrations.CreateModel(
            name='Casino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Title')),
                ('bg', models.CharField(choices=[('blue_bg.jpg', 'Blue'), ('purple_bg.jpg', 'Purple'), ('red_bg.jpg', 'Red'), ('green_bg.jpg', 'Green'), ('yellow_bg.jpg', 'Yellow'), ('azure_bg.jpg', 'Azure'), ('orange_bg.jpg', 'Orange')], default='azure_bg.jpg', help_text='для старого топа', max_length=50, verbose_name='Фон у логотипа')),
                ('license', models.CharField(choices=[('1', 'Curacao'), ('2', 'Malta'), ('3', 'AAMS')], default=2, max_length=3, verbose_name='License')),
                ('logo', easy_thumbnails.fields.ThumbnailerImageField(upload_to='upload/img/logos/', verbose_name='Casino Logo')),
                ('adv1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1')),
                ('adv2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2')),
                ('adv3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3')),
                ('min_dep', models.IntegerField(default=0, verbose_name='Min deposit')),
                ('bonus', models.IntegerField(default=0, verbose_name='Welcome bonus')),
                ('limit', models.IntegerField(default=0, verbose_name='Bonus limit')),
                ('cashback', models.IntegerField(default=0, verbose_name='CashBack %')),
                ('fs', models.IntegerField(default=0, verbose_name='Free Spins')),
                ('click', models.IntegerField(blank=True, default=0, null=True, verbose_name='Clicks')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Last change')),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('badge', models.ForeignKey(blank=True, help_text='для нового топа', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casino_badge', to='top.badge')),
            ],
            options={
                'verbose_name': 'Casino',
                'verbose_name_plural': 'Casinos',
            },
        ),
        migrations.CreateModel(
            name='MailTop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=255, verbose_name='Почта')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailtop_country', to='geo.country')),
            ],
        ),
        migrations.CreateModel(
            name='NameTop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('slug', models.SlugField(default='FILLED-IN-AUTOMATICALLY', max_length=255, unique=True, verbose_name='URL-slug')),
                ('design', models.CharField(choices=[('new', 'New'), ('old', 'Old'), ('betting', 'Betting')], default='new', max_length=50, verbose_name='Design')),
                ('header', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок в шапке (desktop) и title')),
                ('text', models.CharField(blank=True, max_length=300, null=True, verbose_name='Текст (description)')),
                ('promo1', models.CharField(blank=True, help_text='для нового топа', max_length=300, null=True, verbose_name='Текст в шапке (верх)')),
                ('promo2', models.CharField(blank=True, help_text='для нового топа', max_length=300, null=True, verbose_name='Текст в шапке (низ)')),
                ('hide_link', models.BooleanField(blank=True, default=True, verbose_name='Прикрытие ссылок')),
                ('tr_play', models.CharField(blank=True, max_length=24, null=True, verbose_name='Текст на КНОПКЕ')),
                ('tr_bonus', models.CharField(blank=True, max_length=24, null=True, verbose_name='Текст БОНУС')),
                ('tr_fs', models.CharField(blank=True, max_length=24, null=True, verbose_name='Текст ФРИ СПИНЫ')),
                ('tr_cashback', models.CharField(blank=True, max_length=24, null=True, verbose_name='Текст КЭШБЭК')),
                ('tr_info', models.CharField(blank=True, max_length=24, null=True, verbose_name='Текст СИЛЬНЫЕ СТОРОНЫ')),
                ('tr_license', models.CharField(blank=True, max_length=12, null=True, verbose_name='Текст ЛИЦЕНЗИЯ')),
                ('tr_md', models.CharField(blank=True, max_length=24, null=True, verbose_name='Текст МИН ДЕПОЗИТ')),
                ('tr_pay', models.CharField(blank=True, max_length=36, null=True, verbose_name='Текст ПЛАТЕЖКИ')),
                ('tr_score', models.CharField(blank=True, help_text='для нового топа и беттинга', max_length=12, null=True, verbose_name='Текст БАЛЛЫ')),
                ('tr_votes', models.CharField(blank=True, help_text='для нового топа и беттинга', max_length=12, null=True, verbose_name='Текст ГОЛОСА')),
                ('tr_bottom', models.TextField(blank=True, help_text='для беттинга', null=True, verbose_name='Текст ВНИЗУ СТРАНИЦЫ')),
                ('tr_copy', models.TextField(blank=True, null=True, verbose_name='Текст Все права защищены')),
                ('tr_warning', models.TextField(blank=True, help_text='для беттинга', null=True, verbose_name='Текст ПРЕДУПРЕЖДЕНИЕ В САМОМ НИЗУ')),
                ('page_views', models.IntegerField(blank=True, default=0, null=True, verbose_name='Views')),
                ('click', models.IntegerField(blank=True, default=0, null=True, verbose_name='Clicks')),
                ('date_modified1', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время')),
                ('date_modified2', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время')),
                ('date_modified3', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время')),
                ('date_modified4', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время')),
                ('date_modified5', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время')),
                ('thing_modified1', models.TextField(blank=True, null=True, verbose_name='Событие')),
                ('thing_modified2', models.TextField(blank=True, null=True, verbose_name='Событие')),
                ('thing_modified3', models.TextField(blank=True, null=True, verbose_name='Событие')),
                ('thing_modified4', models.TextField(blank=True, null=True, verbose_name='Событие')),
                ('thing_modified5', models.TextField(blank=True, null=True, verbose_name='Событие')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Last change')),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nametop_country', to='geo.country')),
                ('mails', models.ManyToManyField(blank=True, related_name='nameTop_mails', to='top.MailTop')),
            ],
            options={
                'verbose_name': 'Top',
                'verbose_name_plural': 'Tops',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('logo', easy_thumbnails.fields.ThumbnailerImageField(upload_to='upload/img/pay/', verbose_name='logo')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('logo', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='upload/img/soft/', verbose_name='logo')),
            ],
            options={
                'verbose_name': 'Software',
                'verbose_name_plural': 'Softwares',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Источник')),
            ],
        ),
        migrations.CreateModel(
            name='TopPositionCasino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True, default=0, null=True, verbose_name='Position')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Last change')),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('casino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tpc_casino', to='top.casino')),
                ('nameTop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tpc_nametop', to='top.nametop')),
            ],
        ),
        migrations.AddField(
            model_name='nametop',
            name='pay1_highlight',
            field=models.ForeignKey(blank=True, help_text='для нового топа и беттинга', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nametop_pay1', to='top.payment', verbose_name='выделить платежку вверх'),
        ),
        migrations.AddField(
            model_name='nametop',
            name='pay2_highlight',
            field=models.ForeignKey(blank=True, help_text='для нового топа и беттинга', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nametop_pay2', to='top.payment', verbose_name='выделить платежку вниз'),
        ),
        migrations.AddField(
            model_name='nametop',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nameTop_source', to='top.source'),
        ),
        migrations.AddField(
            model_name='nametop',
            name='theme',
            field=models.ForeignKey(blank=True, default=None, help_text='для нового топа', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_theme', to='decor.theme'),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default=None, max_length=255, null=True, verbose_name='Url')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_source', to='top.source')),
            ],
        ),
        migrations.CreateModel(
            name='CountryCasinoSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adv1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1')),
                ('adv2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2')),
                ('adv3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3')),
                ('min_dep', models.IntegerField(default=0, verbose_name='Min deposit')),
                ('bonus', models.IntegerField(default=0, verbose_name='Welcome bonus')),
                ('limit', models.IntegerField(default=0, verbose_name='Bonus limit')),
                ('cashback', models.IntegerField(default=0, verbose_name='CashBack %')),
                ('fs', models.IntegerField(default=0, verbose_name='Free Spins')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Last change')),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ccs_country', to='geo.country')),
                ('link', models.ManyToManyField(blank=True, related_name='ccs_link', to='top.Link')),
                ('pay', models.ManyToManyField(blank=True, related_name='ccs_pays', to='top.Payment')),
            ],
            options={
                'verbose_name': 'Country Casino Setting',
                'verbose_name_plural': 'Country Casino Settings',
            },
        ),
        migrations.AddField(
            model_name='casino',
            name='country',
            field=models.ManyToManyField(blank=True, default=None, related_name='casino_ccs', to='top.CountryCasinoSetting'),
        ),
        migrations.AddField(
            model_name='casino',
            name='link',
            field=models.ManyToManyField(blank=True, related_name='casino_link', to='top.Link'),
        ),
        migrations.AddField(
            model_name='casino',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aff', to='postbacks.partner'),
        ),
        migrations.AddField(
            model_name='casino',
            name='pay',
            field=models.ManyToManyField(blank=True, related_name='pays', to='top.Payment'),
        ),
    ]
