# Generated by Django 3.1.1 on 2022-04-26 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('top', '0002_auto_20220423_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=255, verbose_name='Почта')),
                ('site', models.CharField(max_length=255, verbose_name='Сайт')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailsocial_country', to='geo.country')),
            ],
            options={
                'verbose_name': 'Почта Социалки',
                'verbose_name_plural': 'Почты Социалок',
            },
        ),
    ]
