# Generated by Django 3.1.1 on 2022-05-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0004_auto_20220505_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casino',
            name='limit',
            field=models.IntegerField(default=0, verbose_name='Bonus'),
        ),
    ]
