# Generated by Django 3.1.1 on 2022-05-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0005_auto_20220505_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='nametop',
            name='font_link',
            field=models.TextField(blank=True, help_text='для беттинга', null=True, verbose_name='Ссылка на шрифт заголовка'),
        ),
        migrations.AddField(
            model_name='nametop',
            name='font_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название шрифта'),
        ),
    ]
