# Generated by Django 3.1.1 on 2022-05-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0006_auto_20220512_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nametop',
            name='font_name',
            field=models.CharField(blank=True, help_text='для беттинга', max_length=100, null=True, verbose_name='Название шрифта'),
        ),
    ]
