# Generated by Django 3.1.1 on 2022-05-20 12:58

import colorfield.fields
from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0007_auto_20220512_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='nametop',
            name='badge',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='upload/img/site_badges/', verbose_name='Значок (справа от лого)'),
        ),
        migrations.AddField(
            model_name='nametop',
            name='bg_color',
            field=colorfield.fields.ColorField(blank=True, default='#000000', image_field=None, max_length=7, null=True, samples=None, verbose_name='Цвет фона #RRGGBB'),
        ),
        migrations.AddField(
            model_name='nametop',
            name='bg_img',
            field=easy_thumbnails.fields.ThumbnailerImageField(null=True, upload_to='upload/img/custom/', verbose_name='Фоновое изображение (desktop 1280px)'),
        ),
        migrations.AddField(
            model_name='nametop',
            name='bg_mob_img',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='upload/img/custom/', verbose_name='Фоновое изображение (mobile 480px)'),
        ),
        migrations.AddField(
            model_name='nametop',
            name='bg_tab_img',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='upload/img/custom/', verbose_name='Фоновое изображение (tablet 992px)'),
        ),
        migrations.AddField(
            model_name='nametop',
            name='button_color',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=7, null=True, samples=None, verbose_name='Цвет кнопки'),
        ),
        migrations.AddField(
            model_name='nametop',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=7, null=True, samples=None, verbose_name='Основной цвет #RRGGBB'),
        ),
        migrations.AddField(
            model_name='nametop',
            name='h_color',
            field=colorfield.fields.ColorField(blank=True, default='#FFF000', image_field=None, max_length=7, null=True, samples=None, verbose_name='Цвет хедера #RRGGBB'),
        ),
        migrations.AddField(
            model_name='nametop',
            name='icon_to_top',
            field=models.BooleanField(blank=True, default=False, verbose_name='Иконка GO TO TOP'),
        ),
        migrations.AddField(
            model_name='nametop',
            name='logo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='upload/img/site_logos/', verbose_name='Логотип'),
        ),
    ]
