# Generated by Django 3.1.1 on 2022-05-20 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0001_initial'),
        ('top', '0009_remove_nametop_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nametop',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='nametop',
            name='bg_color',
        ),
        migrations.RemoveField(
            model_name='nametop',
            name='bg_img',
        ),
        migrations.RemoveField(
            model_name='nametop',
            name='bg_mob_img',
        ),
        migrations.RemoveField(
            model_name='nametop',
            name='bg_tab_img',
        ),
        migrations.RemoveField(
            model_name='nametop',
            name='button_color',
        ),
        migrations.RemoveField(
            model_name='nametop',
            name='color',
        ),
        migrations.RemoveField(
            model_name='nametop',
            name='h_color',
        ),
        migrations.RemoveField(
            model_name='nametop',
            name='icon_to_top',
        ),
        migrations.RemoveField(
            model_name='nametop',
            name='logo',
        ),
        migrations.AddField(
            model_name='nametop',
            name='theme',
            field=models.ForeignKey(blank=True, default=None, help_text='для нового топа', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_theme', to='decor.theme'),
        ),
    ]
