# Generated by Django 3.1.1 on 2022-05-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0015_auto_20220520_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nametop',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='nametop',
            name='bg_img',
        ),
        migrations.RemoveField(
            model_name='nametop',
            name='bg_mob_img',
        ),
        migrations.RemoveField(
            model_name='nametop',
            name='bg_tab_img',
        ),
        migrations.RemoveField(
            model_name='nametop',
            name='button_color',
        ),
        migrations.RemoveField(
            model_name='nametop',
            name='logo',
        ),
        migrations.AlterField(
            model_name='nametop',
            name='bg_color',
            field=models.CharField(default='#000000', max_length=7, null=True, verbose_name='Цвет фона #RRGGBB'),
        ),
        migrations.AlterField(
            model_name='nametop',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7, null=True, verbose_name='Основной цвет #RRGGBB'),
        ),
        migrations.AlterField(
            model_name='nametop',
            name='h_color',
            field=models.CharField(default='#FFF000', max_length=7, null=True, verbose_name='Цвет хедера #RRGGBB'),
        ),
    ]
