# Generated by Django 3.1.1 on 2022-05-20 19:40

import colorfield.fields
from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0026_auto_20220520_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='nametop',
            name='bg_color',
            field=colorfield.fields.ColorField(blank=True, default='#000000', image_field=None, max_length=7, null=True, samples=None, verbose_name='Цвет фона #RRGGBB'),
        ),
        migrations.AddField(
            model_name='nametop',
            name='bg_img',
            field=easy_thumbnails.fields.ThumbnailerImageField(null=True, upload_to='upload/img/custom/', verbose_name='Фоновое изображение (desktop 1280px)'),
        ),
        migrations.AddField(
            model_name='nametop',
            name='button_color',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=7, null=True, samples=None, verbose_name='Цвет кнопки'),
        ),
        migrations.AddField(
            model_name='nametop',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=7, null=True, samples=None, verbose_name='Основной цвет #RRGGBB'),
        ),
        migrations.AddField(
            model_name='nametop',
            name='h_color',
            field=colorfield.fields.ColorField(blank=True, default='#FFF000', image_field=None, max_length=7, null=True, samples=None, verbose_name='Цвет хедера #RRGGBB'),
        ),
    ]
