# Generated by Django 3.1.1 on 2022-05-20 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0027_auto_20220520_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nametop',
            name='bg_img',
        ),
    ]
