# Generated by Django 3.1.1 on 2022-05-23 11:27

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0032_auto_20220520_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='nametop',
            name='button_text_color',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=7, null=True, samples=None, verbose_name='Цвет текста кнопки'),
        ),
    ]
