# Generated by Django 3.1.1 on 2022-05-23 11:47

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0034_auto_20220523_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nametop',
            name='bg_img',
            field=easy_thumbnails.fields.ThumbnailerImageField(null=True, upload_to='upload/img/custom/', verbose_name='Фоновое изображение (desktop 1280px)'),
        ),
        migrations.AlterField(
            model_name='nametop',
            name='bg_mob_img',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='upload/img/custom/', verbose_name='Фоновое изображение (mobile 480px)'),
        ),
        migrations.AlterField(
            model_name='nametop',
            name='bg_tab_img',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='upload/img/custom/', verbose_name='Фоновое изображение (tablet 992px)'),
        ),
    ]
