# Generated by Django 3.1.1 on 2022-05-25 15:29

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0035_auto_20220523_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='top3_bg',
            field=easy_thumbnails.fields.ThumbnailerImageField(default='/img/skycrown_bg.png', upload_to='upload/img/top3_bg/', verbose_name='Фон на карточке'),
        ),
        migrations.AlterField(
            model_name='nametop',
            name='design',
            field=models.CharField(choices=[('new', 'New'), ('old', 'Old'), ('betting', 'Betting'), ('top3', 'Top3')], default='new', max_length=50, verbose_name='Design'),
        ),
    ]
