# Generated by Django 3.1.1 on 2022-05-25 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0038_auto_20220525_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casino',
            name='top3_bg',
        ),
    ]
