# Generated by Django 3.1.1 on 2022-05-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0042_nametop_tr_bottom_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nametop',
            name='tr_bottom',
            field=models.TextField(blank=True, help_text='для беттинга и top3', null=True, verbose_name='Текст ВНИЗУ СТРАНИЦЫ'),
        ),
        migrations.AlterField(
            model_name='nametop',
            name='tr_bottom_2',
            field=models.TextField(blank=True, help_text='для беттинга и top3', null=True, verbose_name='Текст ВНИЗУ СТРАНИЦЫ'),
        ),
    ]
