# Generated by Django 3.1.1 on 2022-05-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0043_auto_20220528_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nametop',
            name='tr_bottom_2',
            field=models.TextField(blank=True, help_text='для беттинга и top3 2 Абзац', null=True, verbose_name='Текст ВНИЗУ СТРАНИЦЫ'),
        ),
    ]
