# Generated by Django 3.1.1 on 2022-05-31 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0044_auto_20220529_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nametop',
            name='pay1_highlight',
            field=models.ForeignKey(blank=True, help_text='для нового топа и беттинга', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nametop_pay1', to='top.payment', verbose_name='выделить платежку слева'),
        ),
        migrations.AlterField(
            model_name='nametop',
            name='pay2_highlight',
            field=models.ForeignKey(blank=True, help_text='для нового топа и беттинга', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nametop_pay2', to='top.payment', verbose_name='выделить платежку справа'),
        ),
    ]
