# Generated by Django 3.1.1 on 2022-06-01 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0046_auto_20220601_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casino',
            old_name='pay1_left',
            new_name='pay_left',
        ),
        migrations.RenameField(
            model_name='casino',
            old_name='pay2_right',
            new_name='pay_right',
        ),
    ]
