# Generated by Django 3.1.1 on 2022-06-01 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0047_auto_20220601_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nametop',
            name='pay1_highlight',
        ),
        migrations.RemoveField(
            model_name='nametop',
            name='pay2_highlight',
        ),
    ]
