# Generated by Django 3.1.1 on 2022-06-03 10:11

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0049_auto_20220601_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='color_HEX',
            field=colorfield.fields.ColorField(blank=True, default='#000000', image_field=None, max_length=7, null=True, samples=None, verbose_name='Цвет фона #RRGGBB'),
        ),
    ]
