# Generated by Django 3.1.1 on 2022-06-13 15:02

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0052_nametop_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='nametop',
            name='top4_header',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='upload/img/site_logos/', verbose_name='Логотип в дизайне top4'),
        ),
        migrations.AlterField(
            model_name='nametop',
            name='favicon',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='upload/img/site_logos/', verbose_name='Значок в title'),
        ),
    ]
