# Generated by Django 3.1.1 on 2022-06-17 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('top', '0053_auto_20220613_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toppositionpayment',
            options={'verbose_name': 'Top Position Payment', 'verbose_name_plural': 'Top Position Payments'},
        ),
        migrations.RemoveField(
            model_name='toppositionpayment',
            name='ccs',
        ),
        migrations.AddField(
            model_name='toppositionpayment',
            name='casino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tpp_casino', to='top.casino'),
        ),
        migrations.AddField(
            model_name='toppositionpayment',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tpp_country', to='geo.country'),
        ),
    ]
