# Generated by Django 3.1.1 on 2022-06-22 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0055_link_top'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='top',
        ),
    ]
