# Generated by Django 3.1.1 on 2022-07-07 01:55

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0057_link_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='nametop',
            name='descript_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nametop',
            name='descript_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nametop',
            name='descript_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nametop',
            name='header_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nametop',
            name='header_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nametop',
            name='header_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nametop',
            name='ico_1',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='uploads/img/site_logos/', verbose_name='Иконка 1'),
        ),
        migrations.AddField(
            model_name='nametop',
            name='ico_2',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='uploads/img/site_logos/', verbose_name='Иконка 1'),
        ),
        migrations.AddField(
            model_name='nametop',
            name='ico_3',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='uploads/img/site_logos/', verbose_name='Иконка 1'),
        ),
        migrations.AddField(
            model_name='nametop',
            name='image_1',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='uploads/img/site_logos/', verbose_name='Изображение 1'),
        ),
        migrations.AddField(
            model_name='nametop',
            name='image_2',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='uploads/img/site_logos/', verbose_name='Изображение 1'),
        ),
        migrations.AddField(
            model_name='nametop',
            name='image_3',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='uploads/img/site_logos/', verbose_name='Изображение 1'),
        ),
    ]
