# Generated by Django 3.1.1 on 2022-07-07 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='cloudflare',
            name='NS',
            field=models.CharField(blank=True, max_length=100, verbose_name='NS'),
        ),
        migrations.AlterField(
            model_name='cloudflare',
            name='mail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloudflare_mail', to='domains.mail', verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='cloudflare',
            name='password',
            field=models.CharField(blank=True, max_length=100, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='certificate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='domain_certificate', to='domains.certificate', verbose_name='Сертификат'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='cloak',
            field=models.CharField(max_length=255, verbose_name='Клоака'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='cloud_flare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_cloudflare', to='domains.cloudflare', verbose_name='CloudFlare'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='date_extended',
            field=models.DateTimeField(blank=True, verbose_name='Дата продления'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Вид домена'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_group', to='domains.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='page_proofer',
            field=models.CharField(blank=True, max_length=100, verbose_name='Верстальщик'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='registrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_registrator', to='domains.registrator', verbose_name='Регистратор'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='search_console',
            field=models.BooleanField(default=False, verbose_name='Консоль'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_server', to='domains.server', verbose_name='Сервер'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='sitemap',
            field=models.BooleanField(default=False, verbose_name='Сайтмап'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='mail',
            field=models.CharField(max_length=255, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='password',
            field=models.CharField(blank=True, max_length=100, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='site',
            field=models.CharField(blank=True, max_length=255, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='anydesc',
            field=models.CharField(blank=True, max_length=200, verbose_name='Anydesc'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='number',
            field=models.IntegerField(verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='registrator',
            name='mail',
            field=models.CharField(max_length=255, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='registrator',
            name='password',
            field=models.CharField(blank=True, max_length=100, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='registrator',
            name='phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='registrator',
            name='site',
            field=models.CharField(max_length=255, unique=True, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='server',
            name='ftp_login',
            field=models.CharField(blank=True, max_length=100, verbose_name='FTP Логин'),
        ),
        migrations.AlterField(
            model_name='server',
            name='ftp_password',
            field=models.CharField(blank=True, max_length=100, verbose_name='FTP Пароль'),
        ),
        migrations.AlterField(
            model_name='server',
            name='ip',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ip адрес'),
        ),
        migrations.AlterField(
            model_name='server',
            name='mail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_mail', to='domains.mail', verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='server',
            name='password',
            field=models.CharField(blank=True, max_length=100, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='server',
            name='registrator_site',
            field=models.CharField(blank=True, max_length=100, verbose_name='Сайт Регистратора'),
        ),
    ]
