# Generated by Django 3.1.1 on 2022-04-21 13:54

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('acronym', models.CharField(default=None, max_length=5, null=True, verbose_name='acronym')),
                ('symbol', models.CharField(blank=True, default=None, max_length=5, null=True, verbose_name='symbol')),
                ('logo', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='upload/img/currency/', verbose_name='logo')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='Обозначение (en)')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='upload/img/flags/', verbose_name='Flag')),
                ('currency', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_currency', to='geo.currency')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
    ]
